image: node:10

stages:
  - test

cache:
  paths:
    - node_modules/

test:
  stage: test
  before_script:
    - npm i -g ganache-cli
    - ganache-cli -h localhost -p 8545 2>&1 > ganache-output.log &
  script: 
    - npm install
    - npm run lint
    - npm run test
